name: dynamicsample
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - numpy>=1.17.2
  - python>=3.7
  - pytorch>=1.10.*
  - matplotlib
  - pip
  - pip:
    - kornia
    - pykeops